os:
  - linux

language: php

php:
  - '7.1'

before_script:
  - composer self-update
  - composer install --no-interaction
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit --coverage-text
